name: backend
on:
  push:
    paths:
      - "services/**"
      - "openapi/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "services/**"
      - "openapi/**"
      - ".github/workflows/backend.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
