name: mobile
on:
  push:
    paths:
      - "mobile/**"
      - ".github/workflows/mobile.yml"
  pull_request:
    paths:
      - "mobile/**"
      - ".github/workflows/mobile.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
